WARNING:root:syntax error at or near "SELECR"
LINE 1: SELECR * FROM dataset WHERE vintage='2008'
        ^

INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:03:59] "POST /postgresql/create HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:12:11] "[33mGET /postgresql/update HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /postgresql/update [GET]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'update_table' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:12:53] "[35m[1mGET /postgresql/update HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /postgresql/update [GET]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'update_table' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:13:23] "[35m[1mGET /postgresql/update HTTP/1.1[0m" 500 -
ERROR:main:Exception on /postgresql/update [GET]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'update_table' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:14:01] "[35m[1mGET /postgresql/update HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /postgresql/update [GET]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'update_table' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:15:29] "[35m[1mGET /postgresql/update HTTP/1.1[0m" 500 -
ERROR:main:Exception on /postgresql/update [GET]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'update_table' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:15:34] "[35m[1mGET /postgresql/update HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /postgresql/update [GET]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'update_table' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:16:51] "[35m[1mGET /postgresql/update HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /postgresql/update [GET]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'update_table' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:17:38] "[35m[1mGET /postgresql/update HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /postgresql/update [GET]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'update_table' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:19:14] "[35m[1mGET /postgresql/update HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /postgresql/update [GET]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'update_table' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:21:19] "[35m[1mGET /postgresql/update HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:UPDATE projectt SET Brand = 'Darpan' WHERE Brand = 'Acer'
WARNING:root:column "brand" does not exist
LINE 1: UPDATE projectt SET Brand = 'Darpan' WHERE Brand = 'Acer'
                                                   ^
HINT:  Perhaps you meant to reference the column "projectt.Brand".

INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:21:46] "POST /postgresql/update HTTP/1.1" 200 -
INFO:root:UPDATE projectt SET Brand = 'Darpan' WHERE Brand = 'Acer'
WARNING:root:column "brand" does not exist
LINE 1: UPDATE projectt SET Brand = 'Darpan' WHERE Brand = 'Acer'
                                                   ^
HINT:  Perhaps you meant to reference the column "projectt.Brand".

INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:22:20] "POST /postgresql/update HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:UPDATE projectt SET Brand = 'Darpan' WHERE projectt.Brand = 'Acer'
WARNING:root:column projectt.brand does not exist
LINE 1: UPDATE projectt SET Brand = 'Darpan' WHERE projectt.Brand = ...
                                                   ^
HINT:  Perhaps you meant to reference the column "projectt.Brand".

INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:23:55] "POST /postgresql/update HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:UPDATE projectt SET brand = 'Darpan' WHERE brand = 'Acer'
WARNING:root:column "brand" does not exist
LINE 1: UPDATE projectt SET brand = 'Darpan' WHERE brand = 'Acer'
                                                   ^
HINT:  Perhaps you meant to reference the column "projectt.Brand".

INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:25:18] "POST /postgresql/update HTTP/1.1" 200 -
INFO:root:UPDATE projectt SET brand = 'Darpan' WHERE company = 'acer'
WARNING:root:column "company" does not exist
LINE 1: UPDATE projectt SET brand = 'Darpan' WHERE company = 'acer'
                                                   ^
HINT:  Perhaps you meant to reference the column "projectt.Company".

INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:26:11] "POST /postgresql/update HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:UPDATE projectt SET projectt.Brand = 'Darpan' WHERE projectt.Company = 'acer'
WARNING:root:column projectt.company does not exist
LINE 1: ...DATE projectt SET projectt.Brand = 'Darpan' WHERE projectt.C...
                                                             ^
HINT:  Perhaps you meant to reference the column "projectt.Company".

INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:27:36] "POST /postgresql/update HTTP/1.1" 200 -
INFO:root:UPDATE projectt SET projectt.Brand = 'Darpan' WHERE projectt.Company = 'acer'
WARNING:root:column projectt.company does not exist
LINE 1: ...DATE projectt SET projectt.Brand = 'Darpan' WHERE projectt.C...
                                                             ^
HINT:  Perhaps you meant to reference the column "projectt.Company".

INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:28:55] "POST /postgresql/update HTTP/1.1" 200 -
INFO:root:UPDATE projectt SET projectt.Brand = Darpan WHERE projectt.Company = acer
WARNING:root:column projectt.company does not exist
LINE 1: UPDATE projectt SET projectt.Brand = Darpan WHERE projectt.C...
                                                          ^
HINT:  Perhaps you meant to reference the column "projectt.Company".

INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:29:25] "POST /postgresql/update HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:UPDATE projectt SET projectt.Brand = Darpan WHERE projectt.Company = acer
WARNING:root:column projectt.company does not exist
LINE 1: UPDATE projectt SET projectt.Brand = Darpan WHERE projectt.C...
                                                          ^
HINT:  Perhaps you meant to reference the column "projectt.Company".

INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:30:57] "POST /postgresql/update HTTP/1.1" 200 -
INFO:root:UPDATE projectt SET projectt.Brand = 'Darpan' WHERE projectt.Company = 'acer'
WARNING:root:column projectt.company does not exist
LINE 1: ...DATE projectt SET projectt.Brand = 'Darpan' WHERE projectt.C...
                                                             ^
HINT:  Perhaps you meant to reference the column "projectt.Company".

INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:33:05] "POST /postgresql/update HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:UPDATE projectt SET Brand = 'Darpan' WHERE Company = 'acer'
WARNING:root:column "company" does not exist
LINE 1: UPDATE projectt SET Brand = 'Darpan' WHERE Company = 'acer'
                                                   ^
HINT:  Perhaps you meant to reference the column "projectt.Company".

INFO:werkzeug:127.0.0.1 - - [30/Dec/2022 22:33:59] "POST /postgresql/update HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 19:47:24] "[33mGET / HTTP/1.1[0m" 404 -
WARNING:root:'MongoDB' object has no attribute 'client'
WARNING:root:'MongoDB' object has no attribute 'db'
WARNING:root:'MongoDB' object has no attribute 'col'
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 19:50:52] "POST /mongodb/select HTTP/1.1" 200 -
WARNING:root:'MongoDB' object has no attribute 'client'
WARNING:root:'MongoDB' object has no attribute 'db'
WARNING:root:'MongoDB' object has no attribute 'col'
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 19:52:22] "POST /mongodb/select HTTP/1.1" 200 -
WARNING:root:'MongoDB' object has no attribute 'client'
WARNING:root:'MongoDB' object has no attribute 'db'
WARNING:root:'MongoDB' object has no attribute 'col'
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 19:53:41] "POST /mongodb/select HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
WARNING:root:'MongoDB' object has no attribute 'client'
WARNING:root:'MongoDB' object has no attribute 'db'
WARNING:root:'MongoDB' object has no attribute 'col'
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 19:53:51] "POST /mongodb/select HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
WARNING:root:'MongoDB' object has no attribute 'client'
WARNING:root:'MongoDB' object has no attribute 'db'
WARNING:root:'MongoDB' object has no attribute 'col'
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 19:54:52] "POST /mongodb/select HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
WARNING:root:'MongoDB' object has no attribute 'client'
WARNING:root:'MongoDB' object has no attribute 'db'
WARNING:root:'MongoDB' object has no attribute 'col'
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 19:56:16] "POST /mongodb/select HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:<pymongo.cursor.Cursor object at 0x0000014DEB2F47F0>
ERROR:main:Exception on /mongodb/select [POST]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\darpan\PycharmProjects\api_project\main.py", line 116, in select
    return jsonify(ans)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Cursor is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 20:00:34] "[35m[1mPOST /mongodb/select HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 20:02:06] "POST /mongodb/select HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 20:02:36] "POST /mongodb/select HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:<pymongo.cursor.Cursor object at 0x0000020AD77347C0>
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 20:02:57] "POST /mongodb/select HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:<pymongo.cursor.Cursor object at 0x000001B5DCBC4820>
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 20:03:32] "POST /mongodb/select HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:<pymongo.cursor.Cursor object at 0x0000017FEA8EC910>
ERROR:main:Exception on /mongodb/select [POST]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\darpan\PycharmProjects\api_project\main.py", line 119, in select
    return jsonify(arr)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type ObjectId is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 20:05:33] "[35m[1mPOST /mongodb/select HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:<pymongo.cursor.Cursor object at 0x0000016FA40EC940>
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 20:05:58] "POST /mongodb/select HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:<pymongo.cursor.Cursor object at 0x000001C17F78C940>
ERROR:main:Exception on /mongodb/select [POST]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\darpan\PycharmProjects\api_project\main.py", line 118, in select
    arr.append(i)
AttributeError: 'dict' object has no attribute 'append'
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 20:06:40] "[35m[1mPOST /mongodb/select HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:<pymongo.cursor.Cursor object at 0x00000202C8BE47F0>
ERROR:main:Exception on /mongodb/select [POST]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\darpan\PycharmProjects\api_project\main.py", line 117, in select
    return jsonify(list(ans))
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type ObjectId is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 20:08:08] "[35m[1mPOST /mongodb/select HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:<pymongo.cursor.Cursor object at 0x000001BD08524820>
ERROR:main:Exception on /mongodb/select [POST]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\darpan\PycharmProjects\api_project\main.py", line 117, in select
    return jsonify(list(ans))
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type ObjectId is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 20:08:18] "[35m[1mPOST /mongodb/select HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:<pymongo.cursor.Cursor object at 0x000001EAB0C9C910>
ERROR:main:Exception on /mongodb/select [POST]
Traceback (most recent call last):
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\darpan\PycharmProjects\api_project\main.py", line 117, in select
    return jsonify(dist)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\darpan\anaconda3\envs\api_project\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type ObjectId is not JSON serializable
INFO:werkzeug:127.0.0.1 - - [31/Dec/2022 20:09:25] "[35m[1mPOST /mongodb/select HTTP/1.1[0m" 500 -
